# Generated by Django 4.2.11 on 2024-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distibuter',
            name='doc_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='distibuter',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
