# Generated by Django 4.2.11 on 2024-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerializersApp', '0003_rename_blocked_until_userblock_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='count_num',
            field=models.IntegerField(),
        ),
    ]
